export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export type FETCH_EVENTS_SUCCESS = typeof FETCH_EVENTS_SUCCESS;

export const FETCH_EVENTS_FAIL = 'FETCH_EVENTS_FAIL';
export type FETCH_EVENTS_FAIL = typeof FETCH_EVENTS_FAIL;
